apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: webapplicationtest.azurecr.io/nodetapp:latest
        ports:
        - containerPort: 3002
        env:
        - name: DOTNET_APP_SERVICE
          value: "myapi-deployment.default.svc.cluster.local"  # Fully qualified domain name of the service
        - name: DOTNET_APP_SERVICE_PORT
          value: "80"  # Port exposed by your .NET Core service
