apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the service
      targetPort: 3002  # Port on the container

